### ISSUE TITLE
Ristoratore sketch

### ISSUE THREAD

**Issue by vellons** [vellons/EatAdvisor#4]

**Comment by vellons** [comment]
Sarà una lista di tutti i ristoranti con un bottone che riporta all'interfaccia per crearne uno nuovo

**Comment by vellons** [comment]
1. Il ristoratore si deve loggare [login/create account]
2. Pagina con tutti i ristoranti associati alla ristoratore + Bottone per creare ristoranti

**Comment by manuelmacaj** [comment]
Pagina con tutti i ristoranti associati al ristoratore + bottoni di aggiunta e cancellazione lo trovate nella cartella media. @vellons, ho pensato che sarebbe interessante aggiungere il nome del ristoratore (eventualmente anche un'immagine profilo) sopra al bottone "Aggiungi ristorante". Fammi sapere
